### ISSUE TITLE
no end method for Parser?

### ISSUE THREAD

**Issue by Sheffyp** [ekarak/node-red-contrib-eibd#3]
Hi there!

Thanks so much for putting this together - it looks lots of fun!
I am trying to configure a simple "light on" function and I am having issues writing to knx..

I have set up a simple injector with a string payload with the following payload
{ "dstgad": "1/4/10", "dpt": "DPT1", "value": 1 }
topic: write

linked to a knx out node configured to localhost:6720

But every time I run the injection the server drops off with the following error...

12 May 19:56:22 - [info] Started flows
eibdout.onInput, msg={"topic":"write","payload":"{ \"dstgad\": \"1/4/10\", \"dpt\": \"DPT1\", \"value\": 1 }","_msgid":"38f413a4.c70bec"}
groupAddrWrite dstgad:1/4/10, value:1, dpt:DPT1

Hit the button and ....

EIBD: successfully connected to localhost:6720
formatAPDU value=1 dpt="DPT1"
sendAPDU: "[0,128,1]"
12 May 19:56:45 - [red] Uncaught Exception:
12 May 19:56:45 - TypeError: Object #<Parser> has no method 'end'
    at Connection.end (/usr/lib/node_modules/node-red-contrib-eibd/node_modules/eibd/lib/connection.js:57:17)
    at /usr/lib/node_modules/node-red-contrib-eibd/node_modules/eibd/lib/connection.js:141:10
    at afterWrite (_stream_writable.js:278:3)
    at _stream_writable.js:267:9
    at process._tickCallback (node.js:448:13)

Any ideas?

Thanks

Mark

**Comment by ekarak** [comment]
Hi Mark,
This is a well known bug in the underlying node-eibd library, see
https://github.com/andreek/node-eibd/issues/7

node-eibd is very, well, shallow (!) - it has only the absolutely necessary
features
and I'm always thinking of writing a new driver, namely on the new *knxd*
project
https://github.com/knxd/knxd

Cheers,


2015-05-12 23:00 GMT+03:00 Sheffyp <notifications@github.com>:

> Hi there!
>
> Thanks so much for putting this together - it looks lots of fun!
> I am trying to configure a simple "light on" function and I am having
> issues writing to knx..
>
> I have set up a simple injector with a string payload with the following
> payload
> { "dstgad": "1/4/10", "dpt": "DPT1", "value": 1 }
> topic: write
>
> linked to a knx out node configured to localhost:6720
>
> But every time I run the injection the server drops off with the following
> error...
>
> 12 May 19:56:22 - [info] Started flows
> eibdout.onInput, msg={"topic":"write","payload":"{ \"dstgad\": \"1/4/10\",
> \"dpt\": \"DPT1\", \"value\": 1 }","_msgid":"38f413a4.c70bec"}
> groupAddrWrite dstgad:1/4/10, value:1, dpt:DPT1
>
> Hit the button and ....
>
> EIBD: successfully connected to localhost:6720
> formatAPDU value=1 dpt="DPT1"
> sendAPDU: "[0,128,1]"
> 12 May 19:56:45 - [red] Uncaught Exception:
> 12 May 19:56:45 - TypeError: Object # has no method 'end'
> at Connection.end
> (/usr/lib/node_modules/node-red-contrib-eibd/node_modules/eibd/lib/connection.js:57:17)
> at
> /usr/lib/node_modules/node-red-contrib-eibd/node_modules/eibd/lib/connection.js:141:10
> at afterWrite (_stream_writable.js:278:3)
> at _stream_writable.js:267:9
> at process._tickCallback (node.js:448:13)
>
> Any ideas?
>
> Thanks
>
> Mark
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ekarak/node-red-contrib-eibd/issues/3>.
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by Sheffyp** [comment]
Thanks - do you have any ideas about how I mih resolve it?

**Comment by ekarak** [comment]
I've just published 0.0.3 to NPM, upgraded node-eibd dependency to 0.3.0,
can you please do an 'npm update' please?


2015-05-13 9:24 GMT+03:00 Sheffyp <notifications@github.com>:

> Thanks - do you have any ideas about how I mih resolve it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ekarak/node-red-contrib-eibd/issues/3#issuecomment-101528226>
> .
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by Sheffyp** [comment]
Thanks Elias,

I was just looking through the code and noticed the difference between the
two.

Thanks for resolving so quickly- I'll update and have a go.

M

**Comment by ekarak** [comment]
closing - please reopen if issue still persists.

**Comment by Sheffyp** [comment]
Hi Elias - all runs fine BUT there is a syntax error on line 146 of the 11-eibd.js file. An extra ). Remove this and all runs well!

Thanks
