### ISSUE TITLE
extra character on line 142 in 11-eibd.js

### ISSUE THREAD

**Issue by spants** [ekarak/node-red-contrib-eibd#4]
Line 142 need to remove the extra )

i.e. change from 
});
to 
};

**Comment by ekarak** [comment]
I don't think you're right; this is the proper closing line for a closure for `groupAddrSend` function definition.
https://github.com/ekarak/node-red-contrib-eibd/blob/master/11-eibd.js#L142
Resolving this call - Please reopen with more info on why you think this is a problem.

**Comment by ekarak** [comment]
ooops - Hastily spoken, you're right. Fixing this in a jiffy.

**Comment by ekarak** [comment]
nope - this is actually the closure termination for the call to `initializeEibdSocket`. Resolving call.

**Comment by spants** [comment]
Hi Elias - When I do a       npm install node-red-contrib-eibd   in a dockerfile I get an error. We tried it without using docker and got the same problem. Please see:

http://lime-technology.com/forum/index.php?topic=38486.msg429502#msg429502

What could be wrong?

**Comment by ekarak** [comment]
I just figured out what's wrong, its my fault: you've been fetching code from the NPM, latest version is 0.0.2 and it does indeed have the stray character. I need to publish a new version in NPM.

**Comment by ekarak** [comment]
Hey I've just published a new NPM version, can you please try again?

**Comment by spants** [comment]
Great! - seems to be working now, many thanks!
