### ISSUE TITLE
Possibility to send single consolidated string?

### ISSUE THREAD

**Issue by beireken** [ekarak/node-red-contrib-eibd#5]
Hello,
Your eibd node is functioning great! Thank you very much for creating it!

I was wondering if it was possible to create a single consolidated JSON string to send multiple values to eibd.
Now i am injecting several values from different functions separately to the eibd node. Having everything consolidated before sending to eibd would make my flow a bit cleaner and lessen the load on eibd i believe.

Thx in advance.

**Comment by ekarak** [comment]
Sorry for the late reply, as I've not touched the project in a while. I've been doing some experiments with [knxd, the new knx daemon](https://github.com/knxd/knxd)  that supersedes/extends the old BCU/SDK, and it looks like any new features/development should be made against that.
WRT your problem, have you tried sending the node multiple messages? What you ask is theoretically possible if you have a function node that returns an *array* of messages as follows:
```js
return [{topic: "knx:write", payload: "..."}, {topic: "knx:write", payload: "..."}, ... ];
```

**Comment by beireken** [comment]
Thank you. I will send it via an array as you suggest.
It's just i like to keep things tidy. And connecting a lot of functions 
to 1 node is not that tidy :D

------ Original Message ------
