### ISSUE TITLE
read group address

### ISSUE THREAD

**Issue by beireken** [ekarak/node-red-contrib-eibd#6]
Is the function to read the state of a group address working?
If i inject the following : 
`{"dstgad":"8/1/3"}`

With topic "read" it does not work. It actually writes a 0 to that address.
So if i'm reading the status of a light that is ON, it sends the status to 0 even though the light is on.

Or am i using the read function wrong?

**Comment by ekarak** [comment]
Seems you're right, I've replicated the issue.

**Comment by ekarak** [comment]
found the bug, and updated master.
If you fetch the latest master and retry the read requests are now working.

**Comment by beireken** [comment]
Hmm... i am indeed getting a response now instead of a write. However the value field shows the DPT value.

`knx: response : msg.payload : string [54]
{"srcphy":"15.15.255","dstgad":"1/4/9","value":"DPT1"}`

When i switch a light i get the correct read from the node:

`knx: write : msg.payload : string [59]
{"srcphy":"1.1.14","dstgad":"1/4/9","dpt":"DPT1","value":0}`

**Comment by ozett** [comment]
hi, 
sorry to bother in. but i am trying to get a read from an GA, but i cannot clearly see how the correct syntax is for the inject-node. could you provide a working example with all characters needed {}""?

many thanks. my node is giving me errors in all variants i try... :cry: 
![zwischenablage02](https://cloud.githubusercontent.com/assets/5937811/15085140/bb0e81d6-13d8-11e6-9bd0-c732d6a8b07c.png)

**Comment by ozett** [comment]
solved. 
thing i managed with try and error...
![zwischenablage03](https://cloud.githubusercontent.com/assets/5937811/15086168/2c6de47e-13df-11e6-9a1b-b2095e3dd28b.png)
