### ISSUE TITLE
After a few re-deploys I get multiple messages per datagram

### ISSUE THREAD

**Issue by pakerfeldt** [ekarak/node-red-contrib-eibd#7]
I noticed that after running node-red for a while, and doing a couple of re-deploys I start getting multiple messages from the EIBD node for each datagram. If I restart node-red completely, it gets back to normal.

Is this a known problem?

**Comment by ekarak** [comment]
yes - its related to keeping a persistent TCP connection to eibd (port 3671). I'm currently porting another KNX library for direct access to KNXnet/IP routers (incl. multicast), this will hopefully be ready within the month.

**Comment by pakerfeldt** [comment]
Looking forward to it then. Out of curiosity, what other library will you be using for the new plugin?

**Comment by ekarak** [comment]
It'll be based and hopefully API compatible with https://github.com/estbeetoo/knx.js - but with severely refactored networking code to support multicast.

**Comment by pakerfeldt** [comment]
I have noticed there's another node-red plugin for that knx library. Unfortunately it's not working very well at all for me.

**Comment by ekarak** [comment]
Yes precisely. My attempt at node-eibd + node-red-contrib-eibd sort of
works for me quite reliably but its not what I'd call 'release quality
product'.
I also tried as an experiment the new 'knxd' but it was brittle. While ye
olde eibd car run for *years* unattended, the new knxd is segfaulting like
crazy.

2016-05-13 12:58 GMT+03:00 Patrik Åkerfeldt <notifications@github.com>:

> I have noticed there's another node-red plugin for that knx library.
> Unfortunately it's not working very well at all for me.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/ekarak/node-red-contrib-eibd/issues/7#issuecomment-219002068>
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by pakerfeldt** [comment]
I'd love to track development of the new project as I was planning on writing something similar myself.

**Comment by ekarak** [comment]
How about working on it together?

2016-05-13 13:08 GMT+03:00 Patrik Åkerfeldt <notifications@github.com>:

> I'd love to track development of the new project as I was planning on
> writing something similar myself.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/ekarak/node-red-contrib-eibd/issues/7#issuecomment-219003902>
>



-- 
Elias Karakoulakis
Electrical & Computer Engineer NTUA Athens
Msc Information Systems, AUEB Athens
KNX Advanced Partner

**Comment by pakerfeldt** [comment]
Sure! I'm guessing you have a lot more knowledge about KNX and node-red than I do at this point. But I would love to try to fill in where I can.
